# Generated by Django 3.2.6 on 2021-11-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idade',
        ),
    ]
