# Generated by Django 3.2.6 on 2021-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0002_remove_cliente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
