# Generated by Django 3.2.6 on 2021-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=200)),
                ('price', models.CharField(max_length=8)),
            ],
        ),
    ]
